## write a programe to implement delta rule 

In [1]:
import numpy as np

In [2]:
x=np.zeros((3,))
weights=np.zeros((3,))
desired=np.zeros((3,))
actual=np.zeros((3,))

In [3]:
for i in range(0,3):
    x[i]=float(input("Intial Inputs: "))

Intial Inputs: 1
Intial Inputs: 1
Intial Inputs: 1


In [5]:
for i in range(0,3):
    weights[i]=float(input("Intial weights: "))

Intial weights: 1
Intial weights: 1
Intial weights: 1


In [6]:
for i in range(0,3):
    desired[i]=float(input("Desired output: "))

Desired output: 2
Desired output: 3
Desired output: 4


In [7]:
a=float(input("Enter Learning rate:"))

Enter Learning rate:1


In [8]:
x

array([1., 1., 1.])

In [9]:
weights

array([1., 1., 1.])

In [10]:
desired

array([2., 3., 4.])

In [11]:
actual=x*weights

In [12]:
print("Actual Output",actual)
print("Desired Output",desired)

Actual Output [1. 1. 1.]
Desired Output [2. 3. 4.]


In [13]:
while True:
    if np.array_equal(desired,actual):
        break
    else:
        for i in range(0,3):
            weights[i]=weights[i]+a*(desired[i]-actual[i])
            actual=x*weights

In [15]:
print("Final Output")
print("Corrected weights",weights)
print("Actual output",actual)
print("Desired output",desired)

Final Output
Corrected weights [2. 3. 4.]
Actual output [2. 3. 4.]
Desired output [2. 3. 4.]
