In [1]:
import numpy as np

In [2]:
x1=np.array([1,1,1,-1,1,-1,1,1,1])

In [3]:
b=0

In [4]:
y=np.array([1,-1])

In [5]:
wtold=np.zeros((9,))
wtnew=np.zeros((9,))

In [6]:
wtnew=wtnew.astype(int)
wtold=wtold.astype(int)

In [7]:
wtnew

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
wtold

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

#  Weight update
### W(new)=W(old)+Xi*Y
# Biass update
### b(new)=b(old)+y

In [9]:
print("First input with target =1")
for i in range(0,9):
    wtold[i]=wtold[i]+x1[i]*y[0]
wtnew=wtold
b=b+y[0]

First input with target =1


In [10]:
print("New weights",wtnew)
print("Bias value",b)

New weights [ 1  1  1 -1  1 -1  1  1  1]
Bias value 1


In [11]:
x2=np.array([1,1,1,1,-1,1,1,1,1])
x2

array([ 1,  1,  1,  1, -1,  1,  1,  1,  1])

In [12]:
print("First input with target =1")
for i in range(0,9):
    wtold[i]=wtold[i]+x2[i]*y[1]
wtnew=wtold
b=b+y[1]

First input with target =1


In [13]:
print("New weights",wtnew)
print("Bias value",b)

New weights [ 0  0  0 -2  2 -2  0  0  0]
Bias value 0


In [14]:
# textbool page 37 for reference